export const CART = Object.freeze({
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  ADD_TO_SAVED: "ADD_TO_SAVED",
  REMOVE_FROM_SAVED: "REMOVE_FROM_SAVED",
  MOVE_TO_CART: "MOVE_TO_CART",
});
